# Generated by Django 5.0.7 on 2024-07-25 05:15

import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='established_date',
        ),
        migrations.AddField(
            model_name='school',
            name='established_year',
            field=models.IntegerField(default=1947, validators=[school.validators.validate_year]),
            preserve_default=False,
        ),
    ]
