# Generated by Django 5.0.7 on 2024-07-25 07:38

import student.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(validators=[student.validators.validate_enrollment_date]),
        ),
    ]
